version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - npm run build -- --configuration=production
      - cp appspec.yml dist/
      - cp -r scripts dist/
artifacts:
  base-directory: dist
  files:
    - '**/*'
  secondary-artifacts:
    config:
      files:
       - '**/*'
